name: Hangouts Notification Plugin
description: Provide commands to send events to Google Hangouts Chat Rooms
author: https://github.com/rokt
configuration:
  properties: {}
  additionalProperties: false
