#!/bin/bash
set -euo pipefail

# Set Base Working Directory 
declare -r basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

. "${basedir}/lib/commit_summary.bash"

echo "--- Sending Hangouts Message"

declare -r WEBHOOK_URL="${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_WEBHOOK_URL?}"
declare -r CHAT_URL="${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_CHAT_ENDPOINT?}"
declare -r MESSAGE="${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_MESSAGE?}"

if [[ "${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

if [[ "${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_COMMIT_SUMMARY_ENABLED:-false}" =~ (true|on|1) ]] ; then
    # Generate Commit based message
    declare -r BK_FROM_COMMIT="${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_COMMIT_SUMMARY_FROM_COMMIT}"
    declare -r BK_TO_COMMIT="${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_COMMIT_SUMMARY_TO_COMMIT}"
    declare -r SUMMARY_LOG=$(commit_summary "$BK_FROM_COMMIT" "$BK_TO_COMMIT")
    declare -r MESSAGE="${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_MESSAGE} ${SUMMARY_LOG}"
fi

declare -r CURRENT_COMMIT=$(git rev-parse HEAD)
declare -r THREAD_KEY=${BUILDKITE_PLUGIN_HANGOUTS_NOTIFY_THREAD_KEY:=$CURRENT_COMMIT}

python "${basedir}/lib/send_msg.py" \
    --chat_url "${CHAT_URL}" \
    --web_hook_url "${WEBHOOK_URL}"\
    --thread_key "${THREAD_KEY}"\
    --message "${MESSAGE}"